// Code generated by go generate
// This file was generated by robots at 2018-04-27 15:54:52.32273511 +0000 UTC
package encodeenum

// Encoding is an optional Encoding
type Encoding int

const (
	B64STD Encoding = 1 + iota
	B64URL
	Hex
)

var encoding = [...]string{
	"b64standard", "b64url", "hex",
}

func (e Encoding) String() string {
	return encoding[e-1]
}

/*
Types pulls full list as []string
*/
func (e Encoding) Types() []string {
	return encoding[:]
}
